config/routes.rb
PollywogRanchRailsRuby003::Application.routes.draw do

  get '/frogs/:id/tadpoles/new' => 'tadpoles#new', as: 'new_tadpole'
  delete '/ponds/:id/destroy' => 'ponds#destroy', as: 'delete_pond'
  delete '/frogs/:id/destroy' => 'frogs#destroy', as: 'delete_frog'
  delete '/tadpoles/:id/destroy' => 'tadpoles#destroy', as: 'delete_tadpole'
  get '/tadpoles/:id/evolve' => 'tadpoles#evolve', as: 'evolve_tadpole'
  resources :ponds, :frogs, :tadpoles

  root 'static#index'

  

end

app/models/frog.rb
class Frog < ActiveRecord::Base
  belongs_to :pond
  has_many :tadpoles, dependent: :destroy
end

app/models/pond.rb
class Pond < ActiveRecord::Base
  has_many :frogs, dependent: :destroy
end

app/models/tadpole.rb
class Tadpole < ActiveRecord::Base
  belongs_to :frog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/frogs_controller.rb
class FrogsController < ApplicationController

  def index
    @frogs = Frog.all
  end

  def create
    Frog.create(get_frog_params)
    redirect_to frogs_path
  end

  def new
    @frog = Frog.new
    @ponds = Pond.all
  end

  def show
    @frog = Frog.find(params[:id])
  end

  def edit
    @frog = Frog.find(params[:id])
    @ponds = Pond.all
  end

  def update
    Frog.find(params[:id]).update(get_frog_params)
    redirect_to frogs_path
  end

  def destroy
    Frog.find(params[:id]).destroy
    redirect_to frogs_path
  end

  private

  def get_frog_params
    params.require(:frog).permit(:name, :color, :pond_id)
  end

  # get '/frogs/:id/tadpoles/new' do
  #   # Write the code to find the correct frog
  #   # and redirect to new tadpole form view
  #   @frog = Frog.find(params[:id])
  #   erb :'tadpoles/new'
  # end
end

app/controllers/ponds_controller.rb
class PondsController < ApplicationController

  def index
    @ponds = Pond.all
  end

  def create
    Pond.create(get_pond_params)
    redirect_to ponds_path
  end

  def new
    @pond = Pond.new
  end

  def show
    @pond = Pond.find(params[:id])
  end

  def edit
    @pond = Pond.find(params[:id])
  end

  def update
    Pond.find(params[:id]).update(get_pond_params)
    redirect_to ponds_path
  end

  def destroy
    Pond.find(params[:id]).destroy
    redirect_to ponds_path
  end

  private

  def get_pond_params
    params.require(:pond).permit(:name, :water_type)
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/controllers/tadpoles_controller.rb
class TadpolesController < ApplicationController

  def index
    @tadpoles = Tadpole.all
  end

  def create
    Tadpole.create(get_tadpole_params)
    redirect_to tadpoles_path
  end

  def new
    @tadpole = Tadpole.new
    @frog = Frog.find(params[:id])
  end

  def show
    @tadpole = Tadpole.find(params[:id])
  end

  def edit
    @tadpole = Tadpole.find(params[:id])
    @ponds = Pond.all
  end

  def update
    Tadpole.find(params[:id]).update(get_tadpole_params)
    redirect_to tadpoles_path
  end

  def destroy
    Tadpole.find(params[:id]).destroy
    redirect_to tadpoles_path
  end

  def evolve
    tadpole = Tadpole.find(params[:id])
    Frog.create(:name => tadpole.name, :color => tadpole.color, :pond => tadpole.frog.pond)
    tadpole.destroy
    redirect_to tadpoles_path
  end

  private
  def get_tadpole_params
    params.require(:tadpole).permit(:name, :color, :frog_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frogs_helper.rb
module FrogsHelper
end

app/helpers/ponds_helper.rb
module PondsHelper
end

app/helpers/tadpoles_helper.rb
module TadpolesHelper
end

app/views/frogs/edit.erb
<h1>Edit <%= @frog.name %></h1>
<form action="/frogs/<%= @frog.id %>/update" method="post">
  <label for="name">Name</label>
  <input type="text" id="name" name="frog[name]" placeholder="<%= @frog.name %>">
  <label for="color">Color</label>
  <input type="text" id="color" name="frog[color]" placeholder="<%= @frog.color %>">
  <label for="lives">Lives</label>
  <select id="lives" name="frog[pond_id]">
    <% @ponds.each do |pond| %>
      <option value="<%= pond.id %>"><%= pond.name %></option>
    <% end %>
  </select>
  <input type="submit" value="update">
</form><br>
<a href="/frogs">Cancel</a>

app/views/frogs/edit.html.erb
<h1>Edit <%= @frog.name %></h1>
<%= form_for(@frog) do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name, placeholder: @frog.name %><br />
  <%= f.label :color, "Color" %>
  <%= f.text_field :color, placeholder: @frog.color %>
  <%= f.label :lives, "Lives" %>
  <select id="lives" name="frog[pond_id]">
    <% @ponds.each do |pond| %>
      <option value="<%= pond.id %>"><%= pond.name %></option>
    <% end %>
  </select><br />
  <%= f.submit %>
<% end %>

<%= link_to "Cancel", frogs_path %>

app/views/frogs/index.erb
<%= erb :'layouts/header' %>

<h1>Frogs</h1>
<% @frogs.each do |frog| %>
  <p><a href="/frogs/<%= frog.id %>"><%= frog.name %></a></p>
<% end %>
<p><a href="/frogs/new">Create a new frog</a></p>

<%= erb :'layouts/footer' %>

app/views/frogs/index.html.erb
<%= render 'layouts/header' %>

<h1>Frogs</h1>
<% @frogs.each do |frog| %>
  <p><%= link_to frog.name, frog %></p>
<% end %>
<p><%= link_to "Create a new frog", new_frog_path %></p>

<%= render 'layouts/footer' %>

app/views/frogs/new.erb
<h1>Create a new frog</h1>
<form action="/frogs" method="post">
  <label for="name">Name</label>
  <input type="text" id="name" name="name">
  <label for="color">Color</label>
  <input type="text" id="color" name="color">
  <label for="lives">Lives</label>
  <select id="lives" name="pond_id">
    <% @ponds.each do |pond| %>
      <option value="<%= pond.id %>"><%= pond.name %></option>
    <% end %>
  </select>
  <input type="submit" value="create">
</form><br>
<a href="/frogs">Cancel</a>

app/views/frogs/new.html.erb
<h1>Create a new frog</h1>
<%= form_for(@frog) do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name, placeholder: @frog.name %><br />
  <%= f.label :color, "Color" %>
  <%= f.text_field :color, placeholder: @frog.color %>
  <%= f.label :lives, "Lives" %>
  <%= f.select :pond_id, @ponds.map {|p| [p.name, p.id]} %>
  <%= f.submit %>
<% end %>
<%= link_to "Cancel", frogs_path %>

app/views/frogs/show.erb
<h1><%= @frog.name %> Frog</h1>
<p>Color: <%= @frog.color %></p>
<p>Lives: <a href="/ponds/<%= @frog.pond.id %>"><%= @frog.pond.name %></a></p>
<% unless @frog.tadpoles.empty? %>
  <h2>Children</h2>
  <ol>
    <% @frog.tadpoles.each do |tadpole| %>
      <li><a href="/tadpoles/<%= tadpole.id %>"><%= tadpole.name %></a></li>
    <% end %>
  </ol><br>
<% end %>
<p><strong><a href="/frogs/<%= @frog.id %>/tadpoles/new">Create new tadpole baby</a></strong></p>
<a href="/frogs">Back</a> | 
<a href="/frogs/<%= @frog.id %>/edit">Edit</a> | 
<a href="/frogs/<%= @frog.id %>/destroy">Delete</a>

app/views/frogs/show.html.erb
<h1><%= @frog.name %> Frog</h1>
<p>Color: <%= @frog.color %></p>
<p>Lives: <%= link_to @frog.pond.name, @frog.pond %></p>
<% unless @frog.tadpoles.empty? %>
  <h2>Children</h2>
  <ol>
    <% @frog.tadpoles.each do |tadpole| %>
      <li><%= link_to tadpole.name, tadpole %></li>
    <% end %>
  </ol><br>
<% end %>
<p><strong><%= link_to "Create new tadpole baby", new_tadpole_path(@frog) %></strong></p>
<%= link_to "Back", frogs_path %> | 
<%= link_to "Edit", edit_frog_path(@frog) %> | 
<%= link_to "Delete", delete_frog_path(@frog), method: :delete %>

app/views/layouts/_footer.html.erb
</body>
</html>

app/views/layouts/_header.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Pollywog Ranch</title>
    <link rel="stylesheet" href="/css/style.css">
  </head>
  <body>
    <nav>
      <a href="/ponds">Ponds</a> | 
      <a href="/frogs">Frogs</a> | 
      <a href="/tadpoles">Tadpoles</a>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PollywogRanchRailsRuby003</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/ponds/edit.html.erb
<h1>Edit <%= @pond.name %></h1>
<%= form_for(@pond) do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name, placeholder: @pond.name %><br />
  <%= f.label :water_type, "Water Type" %>
  <%= f.text_field :water_type, placeholder: @pond.water_type %><br />
  <%= f.submit %>
<% end %>

<%= link_to "Cancel", ponds_path %>

app/views/ponds/index.html.erb
<%= render 'layouts/header' %>

<h1>Ponds</h1>
<% @ponds.each do |pond| %>
  <p><%= link_to pond.name, pond %></p>
<% end %>
<p><%= link_to "Create a new pond", new_pond_path %></p>

<%= render 'layouts/footer' %>

app/views/ponds/new.html.erb
<h1>Create a new pond</h1>
<%= form_for(@pond) do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %><br />
  <%= f.label :water_type, "Water Type" %>
  <%= f.text_field :water_type %><br />
  <%= f.submit %>
<% end %>
<%= link_to "Cancel", ponds_path %>

app/views/ponds/show.html.erb
<h1><%= @pond.name %> Pond</h1>
<p>water type: <%= @pond.water_type %></p>
<p>Resident frogs and their tadpoles:</p>
<ol>
  <% @pond.frogs.each do |frog| %>
    <li><%= link_to frog.name, frog %>
      <ol>
        <% frog.tadpoles.each do |tadpole| %>
          <li><%= link_to tadpole.name, tadpole %></li>
        <% end %>
      </ol>
    </li>
  <% end %>
</ol>
<%= link_to "Back", ponds_path %> | 
<%= link_to "Edit", edit_pond_path(@pond) %> | 
<%= link_to "Delete", delete_pond_path(@pond), method: :delete %>

app/views/tadpoles/edit.erb
<h1>Edit <%= @tadpole.name %></h1>
<form action="/tadpoles/<%= @tadpole.id %>/update" method="post">
  <label for="name">Name</label>
  <input type="text" id="name" name="tadpole[name]" placeholder="<%= @tadpole.name %>">
  <label for="color">Color</label>
  <input type="text" id="color" name="tadpole[color]" placeholder="<%= @tadpole.color %>">
  <input type="submit" value="update">
</form><br>
<a href="/tadpoles">Cancel</a>

app/views/tadpoles/edit.html.erb
<h1>Edit <%= @tadpole.name %></h1>
<%= form_for(@tadpole) do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name, placeholder: @tadpole.name %><br />
  <%= f.label :color, "Color" %>
  <%= f.text_field :color, placeholder: @tadpole.color %><br />
  <%= f.submit %>
<% end %>

<%= link_to "Cancel", tadpoles_path %>

app/views/tadpoles/index.erb
<%= erb :'layouts/header' %>

<h1>Tadpoles</h1>
<% @tadpoles.each do |tadpole| %>
  <p><a href="/tadpoles/<%= tadpole.id %>"><%= tadpole.name %></a></p>
<% end %>

<%= erb :'layouts/footer' %>

app/views/tadpoles/index.html.erb
<%= render 'layouts/header' %>

<h1>Tadpoles</h1>
<% @tadpoles.each do |tadpole| %>
  <p><%= link_to tadpole.name, tadpole %></a></p>
<% end %>

<%= render 'layouts/footer' %>

app/views/tadpoles/new.erb
<h1>Create a new tadpole for <%= @frog.name %></h1>
<form action="/tadpoles" method="post">
  <label for="name">Name</label>
  <input type="text" id="name" name="tadpole[name]">
  <input type="hidden" id="color" name="tadpole[color]" value="<%= @frog.color %>">
  <input type="hidden" name="tadpole[frog_id]" value="<%= @frog.id %>">
  <input type="submit" value="create">
</form><br>
<a href="/tadpoles">Cancel</a>

app/views/tadpoles/new.html.erb
<h1>Create a new tadpole for <%= @frog.name %></h1>
<%= form_for(@tadpole) do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %><br />
  <%= f.hidden_field :color, {:value => @frog.color} %>
  <%= f.hidden_field :frog_id, {:value => @frog.id} %>
  <%= f.submit %>
<% end %>

<%= link_to "Cancel", tadpoles_path %>

app/views/tadpoles/show.erb
<h1><%= @tadpole.name %> Tadpole</h1>
<p>color: <%= @tadpole.color %></p>
<p>parent: <a href="/frogs/<%= @tadpole.frog.id %>"><%= @tadpole.frog.name %></a></p>
<p>lives: <a href="/ponds/<%= @tadpole.frog.id %>"><%= @tadpole.frog.pond.name %></a></p>
<p><strong><a href="/tadpoles/<%= @tadpole.id %>/evolve">Evolve to frog</a></strong></p>
<a href="/tadpoles">Back</a> | 
<a href="/tadpoles/<%= @tadpole.id %>/edit">Edit</a> | 
<a href="/tadpoles/<%= @tadpole.id %>/destroy">Delete</a>

app/views/tadpoles/show.html.erb
<h1><%= @tadpole.name %> Pond</h1>
<p>color: <%= @tadpole.color %></p>
<p>parent: <%= link_to @tadpole.frog.name, @tadpole.frog %></p>
<p>lives: <%= link_to @tadpole.frog.pond.name, @tadpole.frog.pond %></p>
<p><strong><%= link_to "Evolve to frog", evolve_tadpole_path(@tadpole) %></p>
<%= link_to "Back", tadpoles_path %> | 
<%= link_to "Edit", edit_tadpole_path(@tadpole) %> | 
<%= link_to "Delete", delete_tadpole_path(@tadpole), method: :delete %>